[run]
dimension=3
tEnd=0.5
nStepmax=100000

# noutput equals -1 means we dump data at every time steps
nOutput=2

[amr]
level_min=3
level_max=6

use_block_data=yes
bx=4
by=4
bz=4

# init step may contain calls to globalRefine
# if the following option is true, we interleave
# calls to load balancing in between globalRefine
# if the following option is false, a single load
# balancing operation is done at the end of
# globalRefine steps
enable_load_balance_during_init=false

# example parameter for using LOHNER_UNSPLIT criterion
refine_criterion=LOHNER_UNSPLIT
epsilon_refine=0.16
epsilon_coarsen=0.02
epsilon_lohner=0.02

# example parameter for using LOHNER_UNSPLIT criterion
#refine_criterion=SIMPLE_GRADIENT
#epsilon_refine=0.1
#epsilon_coarsen=0.01

# p4est connectivity type
connectivity=brick

# control MPI load balancing (number of time steps between two
# consecutive load balancing)
load_balancing_frequency=10

# control AMR cycle frequency (number of time steps between two
# consecutive AMR cycles)
cycle_frequency=10

#
# when using two AMR refinement criterion (one for init conditions,
# one of the rest of the simulation run), we may want to disable the first amr cycle
# to smooth the transition between the two AMR criterion.
#
disable_first_amr_cycle=yes

[p4est_connectivity]
nbrick_x=1
nbrick_y=1
nbrick_z=1

periodic_x=0
periodic_y=0
periodic_z=0

[mesh]
xmin=-0.5
ymin=-0.5
zmin=-0.5
scaling_factor=1.0

boundary_type_xmin=ZERO_GRADIENT
boundary_type_xmax=ZERO_GRADIENT

boundary_type_ymin=ZERO_GRADIENT
boundary_type_ymax=ZERO_GRADIENT

boundary_type_zmin=ZERO_GRADIENT
boundary_type_zmax=ZERO_GRADIENT

[hydro]
cfl=0.8
niter_riemann=10
slope_type=2
problem=blast
riemann=HLLC
use_flux_oriented_computation=yes
use_conservative_update=yes

#
# pressure inside should be
# (gamma-1)*epsilon_sedov/volume
#
# note that volume must be adjusted to the discretize ball (if we don't results will be biased)
#
# where epsilon_sedov is
# - 1d : 0.0673185, volume = 2r
# - 2d : 0.311357, volume = pi r^2
# - 3d : 0.851072, volume = 4/3*pi*r^3
#
# for reference see:
# - https://cococubed.com/papers/kamm_2000.pdf
# - https://cococubed.com/research_pages/sedov.shtml
#
# Please note that pressure inside will be adjusted so that total energy inside
# given by total_energy_inside
[blast]
radius=0.01
total_energy_inside=0.851072
compute_radial_profile=yes
num_radial_bins=1000

[material0]
gamma=1.4
pinf=0.0

[region0]
name=inside
rho=1.0
p=1.0

[region1]
name=outside
rho=1.0
p=1e-7

[output]
outputDir=./
outputPrefix=sedov_blast_3d
outputVtkAscii=false
write_variables=rho,e_tot
write_mesh_info=no
write_iOct=no
hdf5_enabled=yes
enable_writing_leaf_data=no
write_conformal_status=no

[other]
implementationVersion=0
