[run]
dimension=2
tEnd=10.0
nStepmax=3000000

# noutput equals -1 means we dump data at every time steps
nOutput=0

[amr]
level_min=2
level_max=2

use_block_data=yes
bx=16
by=16

# init step may contain calls to globalRefine
# if the following option is true, we interleave
# calls to load balancing in between globalRefine
# if the following option is false, a single load
# balancing operation is done at the end of
# globalRefine steps
enable_load_balance_during_init=false

# example parameter for using LOHNER_UNSPLIT criterion
#refine_criterion=LOHNER_UNSPLIT
#epsilon_refine=0.128
#epsilon_coarsen=0.016
#epsilon_lohner=0.02

# example parameter for using SIMPLE_GRADIENT criterion
refine_criterion=SIMPLE_GRADIENT
epsilon_refine=0.005
epsilon_coarsen=0.001

# p4est connectivity type
connectivity=brick

# control MPI load balancing (number of time steps between two
# consecutive load balancing)
load_balancing_frequency=128

# control AMR cycle frequency (number of time steps between two
# consecutive AMR cycles)
cycle_frequency=10

#
# when using two AMR refinement criterion (one for init conditions,
# one of the rest of the simulation run), we may want to disable the first amr cycle
# to smooth the transition between the two AMR criterion.
#
disable_first_amr_cycle=no

[p4est_connectivity]
nbrick_x=1
nbrick_y=1

periodic_x=1
periodic_y=1

[mesh]
xmin=-5.0
ymin=-5.0
scaling_factor=10.0

boundary_type_xmin=PERIODIC
boundary_type_xmax=PERIODIC

boundary_type_ymin=PERIODIC
boundary_type_ymax=PERIODIC

[hydro]
cfl=0.8
niter_riemann=10
slope_type=2
problem=isentropic_vortex
riemann=HLLC
implementation_version=0

[isentropic_vortex]
density_ambient=1.0
temperature_ambient=1.0
vx_ambient=1.0
vy_ambient=1.0
vz_ambient=1.0

[material0]
gamma=1.666

[output]
outputDir=./
outputPrefix=test_isentropic_vortex_2d
outputVtkAscii=false
write_variables=rho,rho_vx,rho_vy,e_tot
write_mesh_info=no
write_level=yes
write_iOct=no
hdf5_enabled=yes
enable_writing_leaf_data=no
write_conformal_status=no
