# Hypersonic shock diffraction problem.
#
# - unit box
# - fluid at rest at t=0
# - wall border conditions every where except on the left vertical border (x=0, 0.5 < y < 1),
# where high Mach flow is entering the domain
#
# Note: this test case is very similar as "jet"
#
#   ------------------
#   ->               |
#   ->               |
#   ->               |
#   |                |
#   |                |
#   |________________|
#
# References:
# 1. Development of an accurate and robust HLLC-type Riemann solver for all Mach number flows.
# Lijun Hu, Kexin Zhu, Lielong Li, Communications in Nonlinear Science and Numerical Simulation
# Volume 152, Part A, January 2026, 109178
# https://doi.org/10.1016/j.cnsns.2025.109178
#
# 2. A shock-stable modification of the HLLC Riemann solver with reduced numerical dissipation.
# N. Fleischmann, S. Adami, N.A. Adams, J Comput Phys, 423 (2020), Article 109762
# https://doi.org/10.1016/j.jcp.2020.109762
#
# Here we use initial conditions given in section 4.10 of [1].
# The post-shock state can be cross-checked using the Rankine-Hugoniot condition
# for a moving shock using python script tools/moving_shock.py (available in kalypsso's sources)


[run]
dimension=2
tEnd=0.156
nStepmax=100000

# noutput equals -1 means we dump data at every time steps
nOutput=10

[amr]
level_min=2
level_max=6

use_block_data=yes
bx=16
by=16


# init step may contain calls to globalRefine
# if the following option is true, we interleave
# calls to load balancing in between globalRefine
# if the following option is false, a single load
# balancing operation is done at the end of
# globalRefine steps
enable_load_balance_during_init=false

# refine criterion (used during regular dynamics)
# example parameter for using LOHNER_UNSPLIT criterion
refine_criterion=LOHNER_UNSPLIT
epsilon_refine=0.1
epsilon_coarsen=0.125
epsilon_lohner=0.02

# example parameter for using LOHNER_UNSPLIT criterion
#refine_criterion=SIMPLE_GRADIENT
#epsilon_refine=0.1
#epsilon_coarsen=0.01

# p4est connectivity type
connectivity=brick

# control MPI load balancing (number of time steps between two
# consecutive load balancing)
load_balancing_frequency=20

# control AMR cycle frequency (number of time steps between two
# consecutive AMR cycles)
cycle_frequency=10

#
# when using two AMR refinement criterion (one for init conditions,
# one of the rest of the simulation run), we may want to disable the first amr cycle
# to smooth the transition between the two AMR criterion.
#
disable_first_amr_cycle=yes

[p4est_connectivity]
nbrick_x=1
nbrick_y=1

periodic_x=0
periodic_y=0

[mesh]
xmin=0.0
ymin=0.0

scaling_factor=1.0

boundary_type_xmin=WALL
boundary_type_xmax=WALL

boundary_type_ymin=WALL
boundary_type_ymax=WALL

[hydro]
cfl=0.8
niter_riemann=10
slope_type=2
problem=jet
riemann=HLLC
implementation_version=0

[jet]
# inside box (pre-shoc)
rho_inside=1.4
pressure_inside=1.0

# injected fluid state (post shock)
rho=7.041132906907901
u=4.07794695481336
v=0.0
w=0.0
pressure=30.05945

# injection location
y=0.75
width=0.5

[material0]
gamma=1.4

[border]
enable_jet=true

[output]
outputDir=./
outputPrefix=test_shock_diffraction_2d_hllc
outputVtkAscii=false
write_variables=rho,rho_vx,rho_vy,e_tot,rho_schlieren
write_mesh_info=no
write_mesh_level=yes
write_iOct=no
hdf5_enabled=yes
enable_writing_leaf_data=no
write_conformal_status=no
schlieren_scaling=SQRT
